import { type LearningMethod } from "@/lib/types";

export const learningMethods: LearningMethod[] = [
  {
    id: "spaced-repetition",
    title: { zh: "间隔重复法", en: "Spaced Repetition" },
    hook: "在遗忘发生前精准复习，用更少时间记住更多知识。",
    description:
      "基于艾宾浩斯遗忘曲线，间隔重复通过科学安排复习时间来对抗遗忘。它不要求你一次性死记硬背，而是在记忆即将消退时主动提取信息，从而把短期记忆转化为长期记忆。",
    steps: [
      "选择需要记忆的知识点制作卡片或整理到复习清单中。",
      "第1天学习后，在第2天、第4天、第7天和第15天依次复习。",
      "每次复习时先尝试回忆，再看答案，不要直接阅读。",
      "根据掌握程度动态调整间隔：难点缩短，易点拉长。",
      "每天坚持15-20分钟，避免考前突击。",
    ],
    recommendedSubjects: ["英语", "语文", "生物", "历史", "政治", "地理"],
    difficulty: "beginner",
    timePerSession: "20分钟",
    icon: "Repeat",
  },
  {
    id: "active-recall",
    title: { zh: "主动回忆法", en: "Active Recall" },
    hook: "合上书，强迫大脑提取知识，才是真正的高效学习。",
    description:
      "主动回忆又称“测试效应”，指在不看资料的情况下主动从记忆中提取信息。相比反复阅读，它能更快发现知识盲区，强化神经连接，是被认知科学评为最高效的学习策略之一。",
    steps: [
      "读完一章或一个知识点后合上书本。",
      "用白纸写下所有记得的核心概念、公式和逻辑链条。",
      "对照教材找出遗漏、混淆和错误之处。",
      "针对薄弱点重新学习，然后再次进行回忆测试。",
      "将易错点制作成自测卡，定期抽考自己。",
    ],
    recommendedSubjects: ["数学", "物理", "化学", "生物", "历史", "政治"],
    difficulty: "intermediate",
    timePerSession: "30分钟",
    icon: "Brain",
  },
  {
    id: "feynman-technique",
    title: { zh: "费曼技巧", en: "Feynman Technique" },
    hook: "如果你不能简单地讲清楚，说明你还没真正学会。",
    description:
      "费曼技巧要求你把复杂概念用简单语言讲给“小学生”听。在简化解释的过程中，你会暴露理解漏洞，并通过查漏补缺建立更深层次的概念连接。",
    steps: [
      "选择一个你想彻底掌握的知识点。",
      "假装向一个完全不懂的人讲解它，使用大白话和类比。",
      "遇到卡壳或用复杂术语掩盖的地方，回到教材重新学习。",
      "用图示、例子或生活场景重新组织语言。",
      "直到能用三句话把核心逻辑讲明白为止。",
    ],
    recommendedSubjects: ["物理", "数学", "化学", "生物", "地理"],
    difficulty: "intermediate",
    timePerSession: "40分钟",
    icon: "Lightbulb",
  },
  {
    id: "pomodoro",
    title: { zh: "番茄工作法", en: "Pomodoro Technique" },
    hook: "25分钟高度专注，让学习效率翻倍。",
    description:
      "番茄工作法通过25分钟专注学习和5分钟短暂休息交替进行，帮助你克服拖延、维持注意力。它特别适合任务繁重的备考阶段，让大脑在高强度学习中保持清醒。",
    steps: [
      "列出当天要完成的3-5个学习任务。",
      "设定25分钟倒计时，期间只专注一项任务。",
      "闹钟响起后休息5分钟，起身喝水、伸展或远眺。",
      "每完成4个番茄钟，休息15-30分钟。",
      "一天结束后记录完成了几个番茄钟，优化明天的计划。",
    ],
    recommendedSubjects: ["数学", "英语", "语文", "物理", "化学"],
    difficulty: "beginner",
    timePerSession: "25分钟",
    icon: "Clock",
  },
  {
    id: "mind-mapping",
    title: { zh: "思维导图法", en: "Mind Mapping" },
    hook: "用一张图把零散知识变成有结构的知识网络。",
    description:
      "思维导图以中心主题为核心，通过分支、颜色和关键词把知识点可视化。它能帮助你理解概念之间的关系，尤其适合需要整合大量信息的文科和综合科目复习。",
    steps: [
      "在纸中央写下核心主题。",
      "用主分支列出主要章节或核心概念。",
      "在每个分支下添加关键词、公式、例子，避免写长句。",
      "用不同颜色区分类别，用箭头表示因果或递进关系。",
      "完成后遮住分支，尝试凭记忆复述整个框架。",
    ],
    recommendedSubjects: ["历史", "政治", "生物", "地理", "语文", "化学"],
    difficulty: "beginner",
    timePerSession: "35分钟",
    icon: "GitBranch",
  },
  {
    id: "cornell-notes",
    title: { zh: "康奈尔笔记法", en: "Cornell Notes" },
    hook: "一页纸分三区，让课堂笔记变成复习神器。",
    description:
      "康奈尔笔记法将笔记页分为笔记栏、线索栏和总结栏。它强迫你在课后快速提炼关键词、写总结，把被动记录转化为主动加工，显著提高复习效率。",
    steps: [
      "将纸分为左窄右宽两栏，下方留出一行总结区。",
      "课堂时只在右侧记录重点、例题和老师强调的易错点。",
      "课后24小时内，在左侧线索栏写下问题和关键词。",
      "用一张纸盖住右侧，只看左侧线索自问自答。",
      "周末在底部总结栏用一句话概括本页核心内容。",
    ],
    recommendedSubjects: ["数学", "物理", "化学", "历史", "政治", "英语"],
    difficulty: "beginner",
    timePerSession: "30分钟",
    icon: "BookOpen",
  },
  {
    id: "interleaving",
    title: { zh: "交叉练习法", en: "Interleaving Practice" },
    hook: "混在一起练，比一次性刷完同类型题更能提升考场应变能力。",
    description:
      "交叉练习指在一次学习中交替练习不同类型的问题或知识点。虽然开始时会更吃力，但它能训练大脑辨别题型、选择策略，提高在真实考试中的迁移能力。",
    steps: [
      "准备几种不同题型或知识点的练习题。",
      "不按顺序，随机交替做题，例如函数→几何→函数→概率。",
      "每做完一题标注所用知识点和解题思路。",
      "对做错的题，分析是“不会”还是“题型识别错误”。",
      "每周至少安排两次交叉练习，每次集中一个学科。",
    ],
    recommendedSubjects: ["数学", "物理", "化学", "英语"],
    difficulty: "advanced",
    timePerSession: "45分钟",
    icon: "Shuffle",
  },
  {
    id: "error-notebook-review",
    title: { zh: "错题本复盘法", en: "Error Notebook Review" },
    hook: "错题不是失败，而是你最宝贵的提分资源。",
    description:
      "错题本复盘法要求你把每次练习和考试中的错误系统整理，并定期重做错题。通过分析错误原因和反复针对性训练，你能把薄弱环节变成得分点，是高考备考中最具性价比的方法之一。",
    steps: [
      "准备专门的错题本或电子文档，按学科分类。",
      "每道错题记录原题、错误答案、正确答案、错误原因和涉及知识点。",
      "每周固定时间重做一次错题，不看答案独立完成。",
      "对再次做错的题标记为重点，加大复习频率。",
      "考前集中复习错题本，避免在相同地方重复犯错。",
    ],
    recommendedSubjects: ["数学", "物理", "化学", "英语", "语文"],
    difficulty: "intermediate",
    timePerSession: "40分钟",
    icon: "ClipboardList",
  },
];
